//! TIFF format constructor, generated by [`impl_image_handler!`].
//!
//! [`impl_image_handler!`]: super::macros::impl_image_handler

use super::macros::impl_image_handler;

impl_image_handler!(
    format_id = "elide.image.tiff",
    extensions = ["tif", "tiff"],
    content_types = ["image/tiff"],
);
