// Generate `packages/wasm/label.{js,d.ts}` from the builtin label catalog.
//
// The catalog is the single source of truth: `cargo run --example labels`
// (in crates/elide-wasm) prints every builtin label id as a JSON array, and
// this script turns each snake_case id into a PascalCase constant. Run by the
// `wasm-pkg` Make target after `wasm-pack build`.

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "packages", "wasm");

// The label ids, straight from the Rust catalog.
const json = execFileSync(
  "cargo",
  ["run", "--quiet", "--example", "labels", "--package", "elide-wasm"],
  { cwd: root, encoding: "utf8" },
);
const ids = JSON.parse(json);

// snake_case id -> PascalCase constant name.
const pascal = (id) =>
  id
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

const entries = ids.map((id) => [pascal(id), id]);
entries.sort((a, b) => a[0].localeCompare(b[0]));

const header = `// GENERATED by scripts/gen-labels.mjs from the builtin label catalog — do not edit.\n`;

const js =
  header +
  `\n/** The built-in entity labels, by PascalCase name. */\nexport const Label = {\n` +
  entries.map(([name, id]) => `  ${name}: ${JSON.stringify(id)},`).join("\n") +
  `\n};\n`;

const dts =
  header +
  `\n/** The built-in entity labels, by PascalCase name. */\nexport const Label: {\n` +
  entries.map(([name, id]) => `  readonly ${name}: ${JSON.stringify(id)};`).join("\n") +
  `\n};\n`;

writeFileSync(join(out, "label.js"), js);
writeFileSync(join(out, "label.d.ts"), dts);

console.log(`Generated Label with ${entries.length} constants.`);
