//! JPEG handler and loader, generated by [`impl_image_handler!`].
//!
//! [`impl_image_handler!`]: super::macros::impl_image_handler

use super::macros::impl_image_handler;

impl_image_handler!(
    handler = JpegHandler,
    loader = JpegLoader,
    format_id = "elide.image.jpeg",
    extensions = ["jpg", "jpeg"],
    content_types = ["image/jpeg"],
    image_format = image::ImageFormat::Jpeg,
);
