//! PNG handler and loader, generated by [`impl_image_handler!`].
//!
//! [`impl_image_handler!`]: super::macros::impl_image_handler

use super::macros::impl_image_handler;

impl_image_handler!(
    handler = PngHandler,
    loader = PngLoader,
    format_id = "elide.image.png",
    extensions = ["png"],
    content_types = ["image/png"],
    image_format = image::ImageFormat::Png,
);
