//! TIFF handler and loader, generated by [`impl_image_handler!`].
//!
//! [`impl_image_handler!`]: super::macros::impl_image_handler

use super::macros::impl_image_handler;

impl_image_handler!(
    handler = TiffHandler,
    loader = TiffLoader,
    format_id = "elide.image.tiff",
    extensions = ["tif", "tiff"],
    content_types = ["image/tiff"],
    image_format = image::ImageFormat::Tiff,
);
